FROM python:3-slim

# uWSGI support
RUN apt-get update && apt-get install -y build-essential libssl-dev

WORKDIR /

COPY requirements.txt requirements.txt
COPY chores.ini chores.ini
COPY /chores chores

RUN pip install -r requirements.txt

CMD ["uwsgi", "--ini", "chores.ini"]
